name: Deploy static content to Pages

on:
  push:
    branches:
      - main  # 当 main 分支有提交时触发部署
    paths:
      - 'data/**'
  workflow_run:
    workflows: ["Plugin Data Updater"]  # 确保触发的工作流名称正确
    types:
      - completed  # 当 "Plugin Data Updater" 完成后才触发

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload data folder to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: data/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
