name: Plugin Data Updater

on:
  workflow_dispatch:        # 手动触发
  push:                     # 当plugins目录有更新时触发
    paths:
      - 'plugins/**'
  schedule:                 # 定时触发（每小时45分）
    - cron: '45 * * * *'   # 每小时的45分执行

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set timezone to Beijing
      run: |
        sudo timedatectl set-timezone Asia/Shanghai
        echo "Current Time: $(date)"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scraper
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        CACHE_ENABLED: 'true'
      run: |
        python scripts/plugin_scraper.py \
          --timeout 30 \
          --retry 5 || {
          echo "Scraper execution failed" >&2
          exit 1
        }

    - name: 临时保存 data 文件夹
      run: |
        mv data /tmp/data

    - name: 清空所有内容（保留 .git）
      run: |
        find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +

    - name: 恢复 data 文件夹
      run: |
        mv /tmp/data ./data

    - name: 创建无历史的 meta 分支并提交
      run: |
        git checkout --orphan meta
        git add -A
        git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M')" --allow-empty
        git push --force origin meta

    - name: Cleanup
      if: always()
      run: |
        history -c
        rm -rf ~/.bash_history
        echo "Cleanup complete"
